build FEATURE tests options for augyang
sysrepo/augyang pull request #1
Opened 2021-11-30 08:34 UTC by lePici

2021-11-30 14:09 UTC, michalvasko requested changes

2021-11-30 14:09 UTC, michalvasko commented on tests/CMakeLists.txt
> +add_custom_target(ay_new_expected COMMAND ${CMAKE_COMMAND} -E
Do not invoke `cmake` unless you have to, better to use `cp(1)` here because it is well-known.

2021-11-30 14:09 UTC, michalvasko commented on tests/CMakeModules/AYtest.cmake
> +execute_process(COMMAND ${PROJECT_DIR}/build/augyang -O ${YANG_GEN_DIR} ${MOD} RESULT_VARIABLE ret)
Path to `augyang` is way too specific, you should be able to use `$<TARGET_FILE:${augyang}>` directly, `cmake` should replace it with the absolute path to the binary.

2021-11-30 14:18 UTC, lePici commented on tests/CMakeModules/AYtest.cmake
> +execute_process(COMMAND ${PROJECT_DIR}/build/augyang -O ${YANG_GEN_DIR} ${MOD} RESULT_VARIABLE ret)
I tried `$<TARGET_FILE:${augyang}>` but it doesn't work. The augyang will not start.

2021-11-30 14:21 UTC, michalvasko commented on tests/CMakeModules/AYtest.cmake
> +execute_process(COMMAND ${PROJECT_DIR}/build/augyang -O ${YANG_GEN_DIR} ${MOD} RESULT_VARIABLE ret)
Then it seems it is not supported here, too bad. Use `${PROJECT_BINARY_DIR}/augyang` then, the build directory name can be arbitrary, not just `build`.

2021-11-30 14:27 UTC, lePici commented on tests/CMakeModules/AYtest.cmake
> +execute_process(COMMAND ${PROJECT_DIR}/build/augyang -O ${YANG_GEN_DIR} ${MOD} RESULT_VARIABLE ret)
This variable is empty.

2021-12-01 07:43 UTC, michalvasko approved these changes

2021-12-01 07:43 UTC, merged